[workspace.package]
authors = ["Oliver Bøving <oliver@bvng.dk>"]

[workspace]
members = ["server", "silvers"]
resolver = "2"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
